### ISSUE TITLE
Is this something we should know about?

### ISSUE THREAD

**Issue by Grey-Lancaster** [witnessmenow/ESP32-Cheap-Yellow-Display#116] opened 2024-01-19 01:58 UTC
Or do you already know?

https://registry.platformio.org/libraries/rzeldent/esp32_smartdisplay

Grey

**Comment by olivluca** [comment] 2024-04-08 13:12
I actually used it to write my first (and only) CYD project.
I think it should be mentioned somewhere in this repository.

**Comment by olivluca** [comment] 2024-04-08 13:19
This is a duplicate of issue #34

**Closed** 2024-05-17 17:59 UTC
Labels: duplicate
